
version: '3.8'

services:

  shard2svr1:
    container_name: shard2svr1
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /mnt/cims_prod_shard2
    ports:
      - 50004:27017
    volumes:
      - shard2svr1:/mnt/cims_prod_shard2

  shard2svr2:
    container_name: shard2svr2
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /mnt/cims_prod_shard2
    ports:
      - 50005:27017
    volumes:
      - shard2svr2:/mnt/cims_prod_shard2

  shard2svr3:
    container_name: shard2svr3
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /mnt/cims_prod_shard2
    ports:
      - 50006:27017
    volumes:
      - shard2svr3:/mnt/cims_prod_shard2

volumes:
  shard2svr1: {}
  shard2svr2: {}
  shard2svr3: {}

